# Generated by Django 3.2.8 on 2021-10-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
